### ISSUE TITLE
Show loader every requests ?

### ISSUE THREAD

**Issue by hungnguyenfe** [mpalourdio/ng-http-loader#60] opened 2018-04-14 20:11 UTC
I am building a lazy loading app. I want to use Interpreter to show loader every request but it seem doesn't work. 
My HttpInterceptor Class
![capture](https://user-images.githubusercontent.com/34564315/38772249-a5a5dff8-405c-11e8-94f2-c6d445bb50ee.JPG)

And in my App.module
![capture1](https://user-images.githubusercontent.com/34564315/38772254-c165ddce-405c-11e8-9fde-b43319f69d26.JPG)

Everything work fine if I dint use lazy loading :(

**Comment by hanh45** [comment] 2018-04-15 07:29
Not working for Lazy load modules #51

**Comment by mpalourdio** [comment] 2018-04-15 07:55
You don't need to implement your own interceptor as this module registers one for this purpose. But your lazy-loaded modules need to use the same instance of ``HttpClientModule`` as stated in #51 .

Closing as not a bug, but in integration problem.

**Closed by mpalourdio** 2018-04-15 07:55 UTC

**Comment by hungnguyenfe** [comment] 2018-04-16 02:26
Thanks for the feedback.
