### ISSUE TITLE
displaying spinner specific components is not working

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [mpalourdio/ng-http-loader#38] opened 2018-01-19 11:53 UTC
We have configured the dependency in app.module.ts like below.

`import { NgHttpLoaderModule } from 'ng-http-loader/ng-http-loader.module';
@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    LoginRoutingModule,
    AppRoutingModule,
    BrowserAnimationsModule,
	  HttpClientModule,
    NgHttpLoaderModule,
 // NgHttpLoaderComponentsModule,
 // NgHttpLoaderServicesModule,
	DateTimePickerModule,
	ToastModule.forRoot()
	],
`
and we configured <spinner></spinner> in where ever we need that in the html file. Unfortunately the spinner is not showing up.

Thanks...

**Comment by mpalourdio** [comment] 2018-01-19 12:21
Are you tryiing to display a specific spinner with your own show/hide logic, or do you want the default behaviour show/hide with http interceptors and a different spinner than the one by default ?

Can you show me how you integrate the component ? Because all I can see in your snippet is the module loading

**Comment by PrabakarKaruppasamy** [comment] 2018-01-19 12:33
I want default behavior show/hide with http interceptors.
Giving <spinner></spinner> in html page at the starting point of the page.

**Comment by mpalourdio** [comment] 2018-01-19 12:35
You just need 

``<spinner [spinner]="spinkit.skRotatingPlane"></spinner> ``

**Comment by mpalourdio** [comment] 2018-01-21 08:40
Closing as not an issue IMO. Feel free to re-open with a code snippet for reproducing the bug. A failing unit-test case is welcome too.

**Closed by mpalourdio** 2018-01-21 08:40 UTC
Labels: question

**Comment by PrabakarKaruppasamy** [comment] 2018-01-22 06:24
Facing the below issues.

ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'spinner' since it isn't a known property of 'spinner'. ("
</nav>
<div class="main-content">
        <spinner [ERROR ->][spinner]="spinkit.skRotatingPlane"></spinner>
    <router-outlet></router-outlet>
</div>"): ng:///SuperUserModule/SuperuserComponent.html@176:17
'spinner' is not a known element:
1. If 'spinner' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
</nav>
<div class="main-content">
        [ERROR ->]<spinner [spinner]="spinkit.skRotatingPlane"></spinner>
    <router-outlet></router-outlet>
</div>"): ng:///SuperUserModule/SuperuserComponent.html@176:8
Error: Template parse errors:
Can't bind to 'spinner' since it isn't a known property of 'spinner'. ("
</nav>
<div class="main-content">
        <spinner [ERROR ->][spinner]="spinkit.skRotatingPlane"></spinner>
    <router-outlet></router-outlet>
</div>"): ng:///SuperUserModule/SuperuserComponent.html@176:17
'spinner' is not a known element:
1. If 'spinner' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
</nav>
<div class="main-content">
        [ERROR ->]<spinner [spinner]="spinkit.skRotatingPlane"></spinner>
    <router-outlet></router-outlet>
</div>")

**Comment by uthayathasan** [comment] 2018-12-14 14:56
<ng-http-loader [backgroundColor]="'#ff0000'"   [spinner]="spinkit.skWave"  [debounceDelay]="300"
    [minDuration]="300"  [extraDuration]="300"></ng-http-loader>
working fine.
but when run ng-test display following error in chrome Karma
Failed: Template parse errors:
Can't bind to 'backgroundColor' since it isn't a known property of 'ng-http-loader'.
1. If 'backgroundColor' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<ng-http-loader
[ERROR ->][backgroundColor]="'#ff0000'"
    [spinner]="spinkit.skWave"
    [debounceDelay]="300"
"): ng:///DynamicTestModule/AppComponent.html@1:0
Can't bind to 'spinner' since it isn't a known property of 'ng-http-loader'.

**Comment by mpalourdio** [comment] 2018-12-14 15:19
You need to [import NgHttpLoaderModule](https://github.com/mpalourdio/SpringBootAngularHTML5/blob/master/front/src/app/app.component.spec.ts#L19) in your tests too.

**Comment by Jasa-Bcone** [comment] 2019-04-02 06:31
> <ng-http-loader [backgroundColor]="'#ff0000'" [spinner]="spinkit.skWave" [debounceDelay]="300"
> [minDuration]="300" [extraDuration]="300">
> working fine.
> but when run ng-test display following error in chrome Karma
> Failed: Template parse errors:
> Can't bind to 'backgroundColor' since it isn't a known property of 'ng-http-loader'.
> 
> 1. If 'backgroundColor' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
> 2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<ng-http-loader
>    [ERROR ->][backgroundColor]="'#ff0000'"
>    [spinner]="spinkit.skWave"
>    [debounceDelay]="300"
>    "): ng:///DynamicTestModule/AppComponent.html@1:0
>    Can't bind to 'spinner' since it isn't a known property of 'ng-http-loader'.


- [ ] 

**> import { NgHttpLoaderModule } from 'ng-http-loader';**
