### ISSUE TITLE
Spinner is shown after response is returned

### ISSUE THREAD

**Issue by byblik** [mpalourdio/ng-http-loader#57] opened 2018-04-09 22:18 UTC
Somehow spinner is not shown when request is done and shown when response is returned. So it never hides. Eventually spinner is spinning forever because user is not able to access any elements in page. 
Empirically I found that issue in this string
```
 .pipe(debounce(this.handleDebounce.bind(this)))
```
When I comment it, spinner works well.

**Comment by mpalourdio** [comment] 2018-04-10 06:39
Something else is obviously happening here. Please show code/repo that reproduces the problem.

**Comment by byblik** [comment] 2018-04-10 13:09
Hello @mpalourdio. The issue was with angular change detection. 
I may provide a pull request but I have to write tests for that.
Briefly I merged SpinnerVisibility and PendingRequests subscriptions into 1 on the fly and async piped them in template. Also got rid of ngDestroy as it is not needed any more.
spinner-component.ts
```ts
constructor(
        private pendingInterceptorService: PendingInterceptorService, 
        private spinnerVisibilityService: SpinnerVisibilityService
    ) {
        this.visible$ = merge(
            this.pendingInterceptorService.pendingRequestsStatus.pipe(debounce(this.handleDebounce.bind(this))), 
            this.spinnerVisibilityService.visibilityObservable
        );
    }
```

spinner-component.html
```html
<div id="spinner" *ngIf="visible$ | async">
```

**Comment by mpalourdio** [comment] 2018-04-10 13:12
Thanks for feedback. Please close this issue if invalid, and feel free to open a PR with tests if needed.

Please, be aware that at this time, I don't want to break BC anymore, if not really needed, as I plan to release a 1.0.0 soon.

Thanks !

**Comment by mpalourdio** [comment] 2018-04-10 14:34
@byblik BTW, thanks for the "merge" trick. I was not aware of it. I'm implemeting it now, and it makes things much cleaner !!

**Comment by byblik** [comment] 2018-04-10 14:44
@mpalourdio you're welcome :)

**Comment by byblik** [comment] 2018-04-10 14:50
Very pity :(
Are you completely rewriting component due to feature requests?

**Comment by mpalourdio** [comment] 2018-04-10 14:51
What do you mean, not sure I understand ?

**Comment by byblik** [comment] 2018-04-10 14:52
I mean with 0.9.0 version it's quite easy to use async pipe as I showed in code. It works. Do add new features cannot work with it?

**Comment by mpalourdio** [comment] 2018-04-10 14:55
The problem is not using async pipe, the problem is keeping backward compatibility as much as possible.

Using the async pipe means that the ``isSpinnerVisible`` property is not a ``bool`` anymore, but an ``Observable<boolean>``, which can lead to headaches in actual code bases that use this module

**Comment by byblik** [comment] 2018-04-10 15:06
Well, additionally without async pipe I have to call ChangeDetectorRef.ref.markForCheck() to force angular refresh (show/hide) spinner.

**Comment by mpalourdio** [comment] 2018-04-10 15:08
Well, that's weird.... I never experienced such a thing with this module. A full example would be good so I could eventually check

**Comment by byblik** [comment] 2018-04-10 15:12
Unfortunately this is private repo. What I can say that I debugged observables and subscriptions and they look right. Just Angular doesn't refresh adequately when this.isSpinnerVisible is changed. 
Also it's useful to mention that almost all our components use changeDetection - ChangeDetectionStrategy.OnPush, which is very lazy on refresh.

**Comment by mpalourdio** [comment] 2018-04-10 15:14
Oh ``ChangeDetectionStrategy.OnPush`` might lead to force you to force things manually. I've experienced this too :(

**Closed** 2018-12-02 13:37 UTC
Labels: enhancement, waiting for feedback
