### ISSUE TITLE
exculde some url that contains some word

### ISSUE THREAD

**Issue by arahmanali** [mpalourdio/ng-http-loader#28] opened 2017-11-29 11:10 UTC
i have tried **filteredUrlPatterns** but unfortunately it's not working.

My Url:
foo/bar/baz

What i want:
exclude url contains **bar**

**Comment by mpalourdio** [comment] 2017-11-29 11:52
Please show code

**Comment by arahmanali** [comment] 2017-11-30 19:49
what if bar consist in multiple urls like
foo/bar/baz
bar/baz
bar/123

may i use **foo/baz** to consider only specific?

**Comment by mpalourdio** [comment] 2017-11-30 21:24
Sorry but I just don't understand what you want. Please consider being more precise if you want some help. It's an issue tracker here.

This feature works as expected, you mostly have a regex issue IMO.

**Comment by ghiscoding** [comment] 2017-12-01 16:45
If you want to use **foo/baz** to exclude **foo/bar/baz** just use regex `/foo\/.*\/baz/`, you can try Regex on [Regex101](https://regex101.com/)

@arahmanali, I'm curious why did you down vote @mpalourdio, he is doing an awesome job here with providing his free open source project to the world, so why are you down voting him? I think you don't understand what open source project is, you can down vote me as well if that makes you feel happy.

**Comment by mpalourdio** [comment] 2017-12-01 19:25
Closing here, as this is likely not a bug. @arahmanali feel free to reopen if needed, with a true test case or some code that shows the bug.

As @ghiscoding states, I'm glad to help if the issue is correctly and politely described. My free time is like yours, precious.

Consider @ghiscoding advices on regex, as it's certainly what you are missing here.

**Closed by mpalourdio** 2017-12-01 19:25 UTC
Labels: question
